version: '2'
services:
  lft-api-gateway:
    container_name: lft-api-gateway
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    links:
      - mongo
  lft-file-api:
    container_name: lft-file-api
    volumes:
      - "./file-service/uploads:/cpp_server/uploads"
    build:
      context: ./file-service
      dockerfile: ./Dockerfile
    links:
      - lft-api-gateway
      - lft-logging-api
  lft-logging-api:
    container_name: lft-logging-api
    build:
      context: ./logging-service
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    links:
      - mongo
  lft-website:
    container_name: lft-website
    build:
      context: ./website
      dockerfile: ./Dockerfile
    ports:
      - '3000:80'
    restart: 'on-failure'
    links:
      - lft-api-gateway
  mongo:
    container_name: mongo-lft
    image: mongo:4.0
    volumes:
      - "~/data/db:/usr/src/app/data/db"
    command: 'mongod'
