version: '3'
services:
  lft-api-gateway:
    container_name: lft-api-gateway
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    restart: 'on-failure'
    links:
      - mongo
    networks:
      - lft-local
  lft-file-api:
    container_name: lft-file-api
    volumes:
      - "./server/uploads:/cpp_server/uploads"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports: 
      - '5001:5001'
    links:
      - lft-api-gateway
      - lft-logging-api
    networks:
      - lft-local
  lft-logging-api:
    container_name: lft-logging-api
    build:
      context: ./logging-service
      dockerfile: ./Dockerfile
    ports:
      - '5002:5002'
    restart: 'on-failure'
    links:
      - mongo
    networks:
      - lft-local
  lft-website:
    container_name: lft-website
    build:
      context: ./website
      dockerfile: ./Dockerfile
    ports:
      - '3000:80'
    restart: 'on-failure'
    links:
      - lft-api-gateway
    networks:
      - lft-local
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - "~/data/db:/usr/src/app/data/db"
    ports: 
      - '27017:27017'
    networks:
      lft-local:
        ipv4_address: 172.16.0.1
    command: mongod --bind_ip 127.0.0.1,172.16.0.1
networks:
  lft-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.254
