version: '3'
services:
  lft-api-gateway:
    container_name: lft-api-gateway
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    restart: 'on-failure'
    links:
      - mongo
    networks:
      - lft-local
  lft-file-api:
    container_name: lft-file-api
    volumes:
      - "./server/uploads:/cpp_server/uploads"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports: 
      - '5001:5001'
    links:
      - lft-api-gateway
      - lft-logging-api
    networks:
      - lft-local
  lft-logging-api:
    container_name: lft-logging-api
    build:
      context: ./logging-service
      dockerfile: ./Dockerfile
    ports:
      - '5002:5002'
    restart: 'on-failure'
    links:
      - mongo
    networks:
      - lft-local
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - "~/data/db:/usr/src/app/data/db"
    ports: 
      - '27017:27017'
    networks:
      - lft-local
networks:
  lft-local:
      driver: bridge
