#!/bin/bash
function quit_if_script_run_as_root() {
  if [[ $PLATFORM != "docker" && $EUID -eq 0 ]]; then
    echo "Hey don't use sudo thats our job"
    exit 1
  fi
}

# i found the below steps from:
# https://developer.mongodb.com/community/forums/t/problems-trying-to-compile-mongocxx/2084
function install_mongocxx_dependencies() {
  TOP_DIR=$(pwd)
  sudo apt-get install libmongoc-1.0-0 libbson-1.0 cmake libssl-dev libsasl2-dev zlib1g-dev

  wget https://github.com/mongodb/mongo-c-driver/releases/download/1.17.0/mongo-c-driver-1.17.0.tar.gz
  tar xzf mongo-c-driver-1.17.0.tar.gz
  cd mongo-c-driver-1.17.0
  mkdir cmake-build
  cd cmake-build
  cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..
  sudo make install

  git clone https://github.com/mongodb/mongo-cxx-driver.git \
      --branch releases/stable --depth 1
  cd mongo-cxx-driver/build

  sudo cmake .. \
      -DCMAKE_BUILD_TYPE=Release \
      -DBSONCXX_POLY_USE_MNMLSTC=1 \
      -DCMAKE_INSTALL_PREFIX=/usr/local

  sudo make
  sudo make install
  cd $TOP_DIR
  rm -rf mongo-c-driver-1.17.0*
}

function install_served_dependencies() {
  rm -rf served
  git clone https://github.com/evanugarte/served.git
  sudo apt-get install -y libboost-all-dev
}

function install_json_dependencies() {
  if ! [[ -d "SimpleJSON" ]]; then
      mkdir SimpleJSON
  fi
  cd SimpleJSON
  curl https://raw.githubusercontent.com/nbsdx/SimpleJSON/master/json.hpp -o json.hpp
}

function main() {
  quit_if_script_run_as_root
  if [[ "$1" == "-t" || "$1" == "--type" && ! -z $2 ]]; then
    if [ "$2" == "base" ]; then
      # if we are setting up the base image
      echo "Installing mongocxx dependencies only..."
      install_mongocxx_dependencies
    elif [ "$2" == "docker" ]; then
      # if we are building the image derived from the base
      echo "Installing all dependencies except mongocxx..."
      cd lib
      install_served_dependencies
      install_json_dependencies
      cd ..
    fi
  else
    echo "Defaulting to install all dependencies..."
    install_mongocxx_dependencies
    cd lib
    install_served_dependencies
    install_json_dependencies
    cd ..
  fi
}

main $1 $2
