#!/bin/bash
function quit_if_script_run_as_root() {
  if [[ $EUID -eq 0 ]]; then
    echo "Hey don't use sudo thats our job"
    exit 1
  fi
}

function install_rest_sdk_dependencies() {
  sudo apt-get install g++ git libboost-atomic-dev \
   libboost-thread-dev libboost-system-dev \
   libboost-date-time-dev libboost-regex-dev \
   libboost-filesystem-dev libboost-random-dev \
   libboost-chrono-dev libboost-serialization-dev \
   libwebsocketpp-dev openssl libssl-dev ninja-build
}

# i found the below steps from:
# https://developer.mongodb.com/community/forums/t/problems-trying-to-compile-mongocxx/2084
function install_gridfs_dependencies() {
  sudo apt-get install libmongoc-1.0-0 libbson-1.0 cmake libssl-dev libsasl2-dev zlib1g-dev

  wget https://github.com/mongodb/mongo-c-driver/releases/download/1.17.0/mongo-c-driver-1.17.0.tar.gz
  tar xzf mongo-c-driver-1.17.0.tar.gz
  cd mongo-c-driver-1.17.0
  mkdir cmake-build
  cd cmake-build
  cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..
  sudo make install

  git clone https://github.com/mongodb/mongo-cxx-driver.git \
      --branch releases/stable --depth 1
  cd mongo-cxx-driver/build

  sudo cmake .. \
      -DCMAKE_BUILD_TYPE=Release \
      -DBSONCXX_POLY_USE_MNMLSTC=1 \
      -DCMAKE_INSTALL_PREFIX=/usr/local

  sudo make
  sudo make install
}

quit_if_script_run_as_root
install_rest_sdk_dependencies
install_gridfs_dependencies
