#!/bin/bash
function quit_if_script_run_as_root() {
  if [[ $EUID -eq 0 ]]; then
    echo "Hey don't use sudo thats our job"
    exit 1
  fi
}

function install_served_dependencies() {
  git clone git@github.com:evanugarte/served.git
  sudo apt-get install libboost-all-dev
}

function install_json_dependencies() {
  if ! [[ -d "SimpleJSON" ]]; then
      mkdir SimpleJSON
  fi
  cd SimpleJSON
  curl https://raw.githubusercontent.com/nbsdx/SimpleJSON/master/json.hpp -o json.hpp
}

function main() {
  quit_if_script_run_as_root
  cd lib
  install_served_dependencies
  install_json_dependencies
  cd ..
}

main
