#!/bin/bash
function quit_if_script_run_as_root() {
  if [[ $EUID -eq 0 ]]; then
    echo "Hey don't use sudo thats our job"
    exit 1
  fi
}

function install_served_dependencies() {
  git clone git@github.com:evanugarte/served.git
}

quit_if_script_run_as_root
install_served_dependencies

